import type { Template } from "@/lib/types";

/**
 * Catálogo de templates. O banco (tabela public.templates) é a fonte de verdade em produção
 * e pode ser editado pelo admin; esta cópia serve de fallback e de tipagem.
 */
export const TEMPLATES: Template[] = [
  { id: "post-social", name: "Post / Rede Social", description: "Frase de impacto, opinião, print de rede social. 100% tipográfico, sem capa por IA, sai mais barato. Aceita o nome do perfil.", description_en: "Punchy quote, opinion, social-post screenshot. Typography only, no AI cover, cheaper.", category: "geral", layout: "social", palette: { bg: "#0b0b0f", fg: "#ffffff", accent: "#1d9bf0", muted: "#8b98a5", accent2: "#16181c" }, fonts: { display: "Inter", body: "Inter" }, supports_ai_cover: false, sort_order: 1 },
  { id: "insider", name: "Insider", description: "Bastidor, método, 'como eu faço'. Visual editorial premium, título em caixa alta. Escolha fundo preto ou branco.", description_en: "Behind the scenes, method, how-I-do-it. Premium editorial look, uppercase titles.", category: "geral", layout: "insider", palette: { bg: "#0a0a0a", fg: "#f5f5f4", accent: "#d4ff3f", muted: "#a3a3a3", accent2: "#171717" }, fonts: { display: "Bebas Neue", body: "Space Grotesk" }, supports_ai_cover: true, sort_order: 2 },
  { id: "essencial", name: "Essencial", description: "Autoridade e marca pessoal: a capa leva a identidade do perfil (foto, nome e selo) por cima da foto, com a manchete grande embaixo.", description_en: "Authority and personal brand: the cover carries your profile identity over the photo, headline below.", category: "geral", layout: "identity", palette: { bg: "#101014", fg: "#ffffff", accent: "#f5c518", muted: "#b3b3b3", accent2: "#1c1c22" }, fonts: { display: "Montserrat", body: "Inter" }, supports_ai_cover: true, sort_order: 3 },
  { id: "full-texto", name: "Full Texto", description: "Texto grande em fundo colorido, sem imagem: regras, princípios, passo a passo, opinião, thread. Cada card troca a cor de fundo dentro da paleta.", description_en: "Big text on colored background, no image. Each card rotates the palette.", category: "geral", layout: "fulltext", palette: { bg: "#7c3aed", fg: "#ffffff", accent: "#facc15", muted: "#e9d5ff", accent2: "#db2777", cycle: ["#7c3aed", "#db2777", "#0ea5e9", "#16a34a", "#f97316"] }, fonts: { display: "Archivo Black", body: "Inter" }, supports_ai_cover: false, sort_order: 4 },
  { id: "advocacia", name: "Advocacia", description: "Direito, escritório de advocacia, direitos do trabalhador, contratos.", description_en: "Law firms, workers' rights, contracts.", category: "nicho", layout: "niche", palette: { bg: "#0f172a", fg: "#f8fafc", accent: "#c9a227", muted: "#94a3b8", accent2: "#1e293b" }, fonts: { display: "Playfair Display", body: "Inter" }, supports_ai_cover: true, sort_order: 10 },
  { id: "noticias-virais", name: "Notícias Virais", description: "Notícia quente, polêmica, algo que 'parou a internet'. Palavras entre **asteriscos** no título ganham bloco de cor atrás.", description_en: "Hot news, controversy. **Words** in asterisks get a color block.", category: "noticias", layout: "news", palette: { bg: "#000000", fg: "#ffffff", accent: "#ff1744", muted: "#bdbdbd", accent2: "#111111" }, fonts: { display: "Anton", body: "Inter" }, supports_ai_cover: true, sort_order: 11 },
  { id: "marketing", name: "Marketing", description: "Marketing digital, tráfego pago, copy, oferta, funil.", description_en: "Digital marketing, paid traffic, copy, offers, funnels.", category: "nicho", layout: "niche", palette: { bg: "#09090b", fg: "#fafafa", accent: "#a3e635", muted: "#a1a1aa", accent2: "#18181b" }, fonts: { display: "Space Grotesk", body: "Inter" }, supports_ai_cover: true, sort_order: 12 },
  { id: "ia", name: "Inteligência Artificial", description: "Inteligência artificial, automação, ferramentas de IA. Palavras entre **asteriscos** no título ganham bloco de cor.", description_en: "AI, automation, AI tools. **Words** in asterisks get a color block.", category: "nicho", layout: "news", palette: { bg: "#050510", fg: "#f1f5f9", accent: "#22d3ee", muted: "#94a3b8", accent2: "#7c3aed" }, fonts: { display: "Space Grotesk", body: "Inter" }, supports_ai_cover: true, sort_order: 13 },
  { id: "imobiliaria", name: "Imobiliária", description: "Imóveis, financiamento, corretor, primeiro apartamento.", description_en: "Real estate, financing, brokers, first apartment.", category: "nicho", layout: "niche", palette: { bg: "#f8f5f0", fg: "#1c1917", accent: "#b45309", muted: "#78716c", accent2: "#ffffff" }, fonts: { display: "Playfair Display", body: "Inter" }, supports_ai_cover: true, sort_order: 14 },
  { id: "nutricionista", name: "Nutricionista", description: "Nutrição, alimentação, emagrecimento, receitas saudáveis.", description_en: "Nutrition, food, weight loss, healthy recipes.", category: "nicho", layout: "niche", palette: { bg: "#f0fdf4", fg: "#14532d", accent: "#16a34a", muted: "#4d7c5c", accent2: "#ffffff" }, fonts: { display: "Poppins", body: "Poppins" }, supports_ai_cover: true, sort_order: 15 },
  { id: "medicos", name: "Médicos / Hospitalar", description: "Medicina, clínica médica, prevenção, orientação de saúde.", description_en: "Medicine, clinics, prevention, health guidance.", category: "nicho", layout: "niche", palette: { bg: "#f0f9ff", fg: "#0c4a6e", accent: "#0284c7", muted: "#527a94", accent2: "#ffffff" }, fonts: { display: "Montserrat", body: "Inter" }, supports_ai_cover: true, sort_order: 16 },
  { id: "educacao", name: "Educação / Professores", description: "Ensino, professores, concursos, técnicas de estudo.", description_en: "Teaching, teachers, exams, study techniques.", category: "nicho", layout: "niche", palette: { bg: "#fffbeb", fg: "#1f2937", accent: "#f59e0b", muted: "#6b7280", accent2: "#ffffff" }, fonts: { display: "Poppins", body: "Inter" }, supports_ai_cover: true, sort_order: 17 },
  { id: "clinica-estetica", name: "Clínica de Estética", description: "Harmonização facial, procedimentos estéticos, clínica de estética.", description_en: "Facial harmonization, aesthetic procedures.", category: "nicho", layout: "niche", palette: { bg: "#fdf2f8", fg: "#3b0a2a", accent: "#c2185b", muted: "#8a5470", accent2: "#ffffff" }, fonts: { display: "Playfair Display", body: "Poppins" }, supports_ai_cover: true, sort_order: 18 },
  { id: "contabilidade", name: "Contabilidade e Financeiro", description: "Contabilidade, imposto de renda, MEI, finanças de empresa.", description_en: "Accounting, income tax, small business, company finance.", category: "nicho", layout: "niche", palette: { bg: "#0b1220", fg: "#e2e8f0", accent: "#34d399", muted: "#94a3b8", accent2: "#111c33" }, fonts: { display: "Montserrat", body: "Inter" }, supports_ai_cover: true, sort_order: 19 },
  { id: "academia", name: "Academia / Fitness", description: "Treino, academia, personal trainer, hipertrofia.", description_en: "Training, gym, personal trainer, hypertrophy.", category: "nicho", layout: "niche", palette: { bg: "#0a0a0a", fg: "#ffffff", accent: "#ff5722", muted: "#9e9e9e", accent2: "#1a1a1a" }, fonts: { display: "Bebas Neue", body: "Inter" }, supports_ai_cover: true, sort_order: 20 },
  { id: "turismo", name: "Turismo", description: "Viagem, destinos, agência de turismo, roteiros.", description_en: "Travel, destinations, agencies, itineraries.", category: "nicho", layout: "niche", palette: { bg: "#0c4a6e", fg: "#ffffff", accent: "#fbbf24", muted: "#bae6fd", accent2: "#075985" }, fonts: { display: "Montserrat", body: "Inter" }, supports_ai_cover: true, sort_order: 21 },
  { id: "beleza", name: "Beleza e Estética", description: "Cabelo, maquiagem, salão, cuidados com a pele.", description_en: "Hair, makeup, salons, skincare.", category: "nicho", layout: "niche", palette: { bg: "#1a0f14", fg: "#fff1f2", accent: "#fb7185", muted: "#d4a5b0", accent2: "#2a1820" }, fonts: { display: "Playfair Display", body: "Inter" }, supports_ai_cover: true, sort_order: 22 },
  { id: "categoria", name: "Notícias", description: "Notícia factual e séria, jornalismo, cobertura de acontecimento.", description_en: "Factual, serious news, journalism, event coverage.", category: "noticias", layout: "news", palette: { bg: "#ffffff", fg: "#111111", accent: "#c62828", muted: "#616161", accent2: "#f5f5f5" }, fonts: { display: "Playfair Display", body: "Inter" }, supports_ai_cover: true, sort_order: 23 },
  { id: "dentistas", name: "Dentistas", description: "Odontologia, implante, ortodontia, clareamento.", description_en: "Dentistry, implants, orthodontics, whitening.", category: "nicho", layout: "niche", palette: { bg: "#ecfeff", fg: "#164e63", accent: "#06b6d4", muted: "#5b8a96", accent2: "#ffffff" }, fonts: { display: "Poppins", body: "Inter" }, supports_ai_cover: true, sort_order: 24 },
  { id: "joias", name: "Joias e Semijoias", description: "Joias, semijoias, relógios, produto de luxo.", description_en: "Jewelry, watches, luxury products.", category: "nicho", layout: "niche", palette: { bg: "#0c0a09", fg: "#fafaf9", accent: "#d4af37", muted: "#a8a29e", accent2: "#1c1917" }, fonts: { display: "DM Serif Display", body: "Inter" }, supports_ai_cover: true, sort_order: 25 },
  { id: "pets", name: "Pets", description: "Cães, gatos, pet shop, veterinária, adestramento.", description_en: "Dogs, cats, pet shops, vets, training.", category: "nicho", layout: "niche", palette: { bg: "#fff7ed", fg: "#431407", accent: "#ea580c", muted: "#9a6a4f", accent2: "#ffffff" }, fonts: { display: "Poppins", body: "Poppins" }, supports_ai_cover: true, sort_order: 26 },
];

export const TEMPLATE_IDS = TEMPLATES.map((t) => t.id);

export function getTemplate(id: string, list: Template[] = TEMPLATES): Template {
  return list.find((t) => t.id === id) ?? list[0];
}

/** Fontes disponíveis para render (arquivos em public/fonts). */
export const FONT_FILES: Record<string, { regular: string; bold: string }> = {
  Inter: { regular: "Inter-Regular.ttf", bold: "Inter-ExtraBold.ttf" },
  Montserrat: { regular: "Montserrat-Regular.ttf", bold: "Montserrat-Black.ttf" },
  "Space Grotesk": { regular: "SpaceGrotesk-Regular.ttf", bold: "SpaceGrotesk-Bold.ttf" },
  "Playfair Display": { regular: "PlayfairDisplay-Regular.ttf", bold: "PlayfairDisplay-Black.ttf" },
  Poppins: { regular: "Poppins-Regular.ttf", bold: "Poppins-Bold.ttf" },
  "Bebas Neue": { regular: "BebasNeue-Regular.ttf", bold: "BebasNeue-Regular.ttf" },
  "DM Serif Display": { regular: "DMSerifDisplay-Regular.ttf", bold: "DMSerifDisplay-Regular.ttf" },
  "Archivo Black": { regular: "ArchivoBlack-Regular.ttf", bold: "ArchivoBlack-Regular.ttf" },
  Anton: { regular: "Anton-Regular.ttf", bold: "Anton-Regular.ttf" },
};
export const FONT_NAMES = Object.keys(FONT_FILES);
